### ISSUE TITLE
JSON EXCEPTION

### ISSUE THREAD

**Issue by sheheryar25** [rastating/DroidBeard#285]
05-03 14:45:34.710: E/My String(1087): string result :[<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
05-03 14:45:34.710: E/My String(1087): <HTML><HEAD><TITLE>Not Found</TITLE>
05-03 14:45:34.710: E/My String(1087): <META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
05-03 14:45:34.710: E/My String(1087): <BODY><h2>Not Found</h2>
05-03 14:45:34.710: E/My String(1087): <hr><p>HTTP Error 404. The requested resource is not found.</p>
05-03 14:45:34.710: E/My String(1087): </BODY></HTML>
05-03 14:45:34.710: E/My String(1087): ] and its length is :309
05-03 14:45:34.720: E/Json Exception(1087): Value <!DOCTYPE of type java.lang.String cannot be converted to JSONArray

**Comment by rastating** [comment]
Can you provide a screenshot of your settings or type them up (excluding the API key)?
