### ISSUE TITLE
Add Local Network option

### ISSUE THREAD

**Issue by blakadder** [rastating/DroidBeard#42]
Option to specify home network of the SickBeard server. When connected to that specific SSID DroidBeard would connect to SickBeard through the local IP address also specified in settings

**Comment by rastating** [comment]
Hey @blakadder - this functionality is in the latest beta release, to an extent. You can create and switch between profiles, but it won't currently automatically switch based on WiFi SSID.

**Comment by blakadder** [comment]
Good enough!
